version: 2
id: app.antran.IndieApps
name: Indie Apps Showcases
shortDescription: A platform to discuss about your side projects.
description: |- 
  Have you worked on some side projects but couldn't finish them becasue you lost interest quickly?
  Do you have a cool product but you can't find any early testers/adopters?

  This is a platform to showcase your projects as early as possible to other fellow developers/early adopters.

  Sharing your projects early is very helpful to keep you motivated, to gather early feedbacks and to adapt your projects to serve not only you but also others.  
links:
  - type: homepage
    value: https://antranapp.github.io/IndieApps/
  - type: testflight
    value: https://testflight.apple.com/join/GcUf22Zs
previews:
  - type: iOS
    value: [https://raw.githubusercontent.com/antranapp/AnSwift/master/assets/indie_apps/screenshot1.png, https://raw.githubusercontent.com/antranapp/AnSwift/master/assets/indie_apps/screenshot2.png, https://raw.githubusercontent.com/antranapp/AnSwift/master/assets/indie_apps/screenshot3.png]
releaseNotes:
  - version: 1.0.0 (4)
    note: |- 
      * Very basic UI.
      * Use a git repository as database.
      * User can update the database manually in the setting screen.
      * User can reset the database when something goes wrong.
createdAt: 2020-06-06
updatedAt: 2020-06-06