version: 2
id: io.swift-evolution.app
name: EVOlution - App
shortDescription: Unofficial Swift Evolution app
description: |- 
  EVOlution App is an unofficial app to guide you through all Swift Evolution proposals created by the Swift community.
links:
  - type: homepage
    value: https://landing.evoapp.io/
  - type: appstore
    value: https://apps.apple.com/app/evolution-app/id1210898168
  - type: sourcecode
    value: https://github.com/Evolution-App/iOS
previews:
  - type: iOS
    value: 
      - https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/6c/ba/03/6cba03fa-f85d-75ba-aa01-5f2d135e0b56/pr_source.png/460x0w.png
      - https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/7b/3c/ed/7b3ced8e-fc00-4752-a724-fe4ba998854b/pr_source.png/460x0w.png
      - https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/50/df/ef/50dfef2b-4ee5-4a1b-3a1d-f13f619fd989/pr_source.png/460x0w.png
      - https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/59/36/e2/5936e204-78a0-5d60-babc-0ca255f57fb3/pr_source.png/230x0w.png
releaseNotes:
  - version: 1.3
    note: |- 
      - Support to Dark Mode (thanks to Anton Kuzmin)
      - New Swift Evolution status: Previewing
      - Improved the way to read proposals without huge font sizes.
createdAt: 2020-06-16
updatedAt: 2020-06-16
