version: 2
id: app.antran.MinimalistTodo
name: Todos for Minimalist
shortDescription: A minimal todo list app
description: |- 
  A todo list app for minimalists. 
  One list, one flow, no multitasking.
links:
  - type: homepage
    value: https://antran.app
  - type: testflight
    value: https://antran.app
  - type: appstore
    value: https://antran.app    
releaseNotes:
  - id: 1.0.0 (20)
    version: 1.0.0 (20)
    note: Enable CloudKit
  - id: 1.0.0 (19)
    version: 1.0.0 (19)
    note: Fix some bugs 
createdAt: 2020-06-06
updatedAt: 2020-06-06