name: PullRequest

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Validation

    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache SPM
        uses: actions/cache@v1
        id: spmbuild
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}

      - name: Testing....display available Xcodes on the Server
        run: ls /Applications | grep Xcode

      - name: Force xcode 11 
        run: sudo xcode-select -switch /Applications/Xcode_11.5.app

      - name: List Simulators
        run: xcrun instruments -s
      
      - name: List SDK
        run: xcodebuild -showsdks
        
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          swift build --package-path scripts/ContentTools

      - name: Run
        run: |
          swift run --package-path scripts/ContentTools ContentTools
